version: "3.8"
services:
    api:
        build:
          context: .
          dockerfile: Dockerfile
        container_name: rest_api
        ports:
          - "80:80"
        environment:
          - 'ASPNETCORE_HTTP_PORTS=80'
        depends_on:
          - db
        networks:
          - localnet
    db:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        container_name: mssql1
        ports:
          - "1433:1433"
        environment:
            MSSQL_SA_PASSWORD: "S3cur3P@ssW0rd!"
            ACCEPT_EULA: "Y"
        networks:
          - localnet
networks:
    localnet:
        name: localnet
        driver: bridge